pipeline {
    agent {
        docker {
            image 'jenkins/jnlp-agent-docker'
            args '-v /var/run/docker.sock:/var/run/docker.sock -u root'
        }
    }
    environment {
        DOCKER_TAG_NAME = 'metaph3r/weather-app:latest'
    }

    stages {
        stage('Build') {
            steps {
                checkout scm
                def app = docker.build(${DOCKER_TAG_NAME},'./web-server')
            }
        }
    }
}