pipeline {
    agent {
        docker {
            image 'jenkins/jnlp-agent-docker'
            args '-v /var/run/docker.sock:/var/run/docker.sock -u root'
        }
    }
    stages {
        stage('Build') {
            steps {
                script {
                    checkout scm
                    sh 'docker build -t metaph3r/weather-app:${BUILD_ID} ./web-server'
                    sh 'docker tag  metaph3r/weather-app:${BUILD_ID}  metaph3r/weather-app:latest'
                }
            }
        }
    }
}