# Use root/example as user/password credentials
version: "3.8"

services:
  nginx:
    build: nginx
    ports:
      - 8080:80
  redis:
    image: redis:6.2.6-alpine3.14
  app01:
    build: .
    depends_on:
      - nginx
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  app02:
    build: .
    depends_on:
      - nginx
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379