pipeline {
    agent { 
        docker { image 'docker:latest'}
     }
    node {
        checkout scm
        
        docker.withRegistry('https://hub.docker.com/', '4a3578db-27d2-4f61-baea-724244ec78e6') {
            def chatAppImage = docker.build("chat-app:${env.BUILD_ID}")
            chatAppImage.push()
            chatAppImage.push('latest')
        }
    }
}