name: Deploy chat-app to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: metaph3r/chat-app

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: chat-app
          push: true
          tags: ${{ steps.meta.outputs.tags }},metaph3r/chat-app:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy-kubernetes:
    name: Deploy chat-app to Kubernetes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chat-app/kubernetes
    needs: docker-build-push
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set Kubernetes context
        id: context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: kubernetes-1

      - name: Set up chat-app namespace
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: |
            ./namespace.yml
          kubectl-version: latest

      - name: Set up cert-manager
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: |
            cert-manager.yml
            cluster-issuer.yml
          kubectl-version: latest

      - name: Deploy chat-app application
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: |
            redis.yml
            chat-app.yml
            ingress.yml
          kubectl-version: latest
